name: "📝 Task Assignment"
description: Create a new ticket for a new task assignment
title: "📝 [TASK] - <title>"
labels: [
  "task"
]
body:
  - type: input
    id: start_date
    attributes:
      label: "Start Date"
      description: Start of development
      placeholder: "month/day/year"
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Provide a description for the task
      placeholder: "Topics"
    validations:
      required: false
